from tkinter import *
project=Tk()
project.config(bg="green")
project.title("Login Page using Tkinter")
w=Label(project,text="Please Login",bg="green").place(x=150,y=0)
project.geometry('400x550')
user_name=Label(project,text="User Name",bg="green").place(x=40,y=60)
user_pass=Label(project,text="Password",bg="green").place(x=50,y=100)
username=Entry(project)
passw=Entry(project)
username.place(x=130,y=60)
passw.place(x=130,y=100)
Label(project,text="Forgot Password?",bg="green").place(x=100,y=180)
b1= Button(project,text='LOGIN',width=10,command=project.destroy,activebackground="Blue").place(x=100,y=150)
project.mainloop()
